const ADD_TRANSACTION = 'ADD_TRANSACTION';
const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
const FETCH_TRANSACTION_BY_ID = 'FETCH_TRANSACTION_BY_ID';

export {ADD_TRANSACTION,REMOVE_TRANSACTION,UPDATE_TRANSACTION,FETCH_TRANSACTIONS,FETCH_TRANSACTION_BY_ID};