const ADD_VENDOR = 'ADD_VENDOR';
const FETCH_VENDORS = 'FETCH_VENDORS';
const DELETE_VENDOR = 'DELETE_VENDOR';
const UPDATE_VENDOR = 'UPDATE_VENDOR';

export {ADD_VENDOR, FETCH_VENDORS, DELETE_VENDOR, UPDATE_VENDOR};